version: '3'
 
services:
  db:
    image: mariadb:latest
    container_name: my_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: create_your_db
      MYSQL_USER: your_user_here
      MYSQL_PASSWORD: create_password
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: my_phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
    
  web:
    container_name: my_php
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/Projects/repo:/var/www/html
    links:
      - db